groups:
- name: ceph-mgr-status
  rules:
  - alert: CephMgrIsAbsent
    annotations:
      description: Ceph Manager has disappeared from Prometheus target discovery.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmgrisabsent
    expr: |
      absent(up{job="ceph"} == 1)
    for: 5m
    labels:
      severity: warning
  - alert: CephMgrIsMissingReplicas
    expr: |
      sum(up{job="ceph"}) < 3
    for: 5m
    annotations:
      description: Ceph Manager is missing replicas.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmgrismissingreplicas
    labels:
      severity: warning
- name: ceph-mds-status
  rules:
  - alert: CephMdsMissingReplicas
    annotations:
      description: Minimum required replicas for storage metadata service not available.
        Might affect the working of storage cluster.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmdsmissingreplicas
    expr: |
      sum(ceph_mds_metadata{job="ceph"} == 1) < 2
    for: 5m
    labels:
      severity: warning
- name: quorum-alert.rules
  rules:
  - alert: CephMonQuorumAtRisk
    annotations:
      description: Storage cluster quorum is low. Contact Support.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonquorumatrisk
    expr: |
      count(ceph_mon_quorum_status{job="ceph"} == 1) <= ((count(ceph_mon_metadata{job="ceph"}) % 2) + 1)
    for: 15m
    labels:
      severity: critical
  - alert: CephMonHighNumberOfLeaderChanges
    annotations:
      description: 'Ceph Monitor "{{ $labels.job }}": instance {{ $labels.instance
        }} has seen {{ $value }} leader changes per minute recently.'
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonhighnumberofleaderchanges
    expr: |
      rate(ceph_mon_num_elections{job="ceph"}[5m]) * 60 > 0.95
    for: 5m
    labels:
      severity: warning
- name: ceph-node-alert.rules
  rules:
  - alert: CephNodeDown
    annotations:
      description: Storage node {{ $labels.node }} went down. Please check the node
        immediately.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephnodedown
    expr: |
      cluster:ceph_node_down:join_kube == 0
    for: 30s
    labels:
      severity: critical
- name: osd-alert.rules
  rules:
  - alert: CephOSDDiskNotResponding
    annotations:
      description: Disk device {{ $labels.device }} not responding, on host {{ $labels.host
        }}.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosddisknotresponding
    expr: |
      label_replace((ceph_osd_in == 1 and ceph_osd_up == 0),"disk","$1","ceph_daemon","osd.(.*)") + on(ceph_daemon) group_left(host, device) label_replace(ceph_disk_occupation,"host","$1","exported_instance","(.*)")
    for: 1m
    labels:
      severity: critical
  - alert: CephOSDDiskUnavailable
    annotations:
      description: Disk device {{ $labels.device }} not accessible on host {{ $labels.host
        }}.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosddiskunavailable
    expr: |
      label_replace((ceph_osd_in == 0 and ceph_osd_up == 0),"disk","$1","ceph_daemon","osd.(.*)") + on(ceph_daemon) group_left(host, device) label_replace(ceph_disk_occupation,"host","$1","exported_instance","(.*)")
    for: 1m
    labels:
      severity: critical
  - alert: CephDataRecoveryTakingTooLong
    annotations:
      description: Data recovery has been active for more than 2h. Contact Support.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephdatarecoverytakingtoolong
    expr: |
      ceph_pg_undersized > 0
    for: 2h
    labels:
      severity: warning
  - alert: CephPGRepairTakingTooLong
    annotations:
      description: Self heal operations taking too long. Contact Support.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgrepairtakingtoolong
    expr: |
      ceph_pg_inconsistent > 0
    for: 1h
    labels:
      severity: warning
- name: cluster-state-alert.rules
  rules:
  - alert: CephClusterErrorState
    annotations:
      description: Storage cluster is in error state for more than 10m.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclustererrorstate
    expr: |
      ceph_health_status{job="ceph"} > 1
    for: 10m
    labels:
      severity: critical
  - alert: CephClusterWarningState
    annotations:
      description: Storage cluster is in warning state for more than 10m.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclusterwarningstate
    expr: |
      ceph_health_status{job="ceph"} == 1
    for: 10m
    labels:
      severity: warning
  - alert: CephOSDVersionMismatch
    annotations:
      description: There are {{ $value }} different versions of Ceph OSD components
        running.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosdversionmismatch
    expr: |
      count(count(ceph_osd_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 10m
    labels:
      severity: warning
  - alert: CephMonVersionMismatch
    annotations:
      description: There are {{ $value }} different versions of Ceph Mon components
        running.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonversionmismatch
    expr: |
      count(count(ceph_mon_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 10m
    labels:
      severity: warning
- name: cluster-utilization-alert.rules
  rules:
  - alert: CephClusterNearFull
    annotations:
      description: Storage cluster utilization has crossed 85%.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclusternearfull
    expr: |
      sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.85
    for: 5m
    labels:
      severity: warning
  - alert: CephClusterCriticallyFull
    annotations:
      description: Storage cluster utilization has crossed 95%.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclustercriticallyfull
    expr: |
      sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.95
    for: 5m
    labels:
      severity: critical
- name: ceph-pg
  rules:
  - alert: CephPGAreNotActive
    annotations:
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgarenotactive
    expr: |
      ceph_pg_total{job="ceph"} - ceph_pg_active{job="ceph"} != 0
    labels:
      severity: critical
  - alert: CephPGAreUnclean
    annotations:
      description: Placement groups contain objects that are not replicated the desired
        number of times. They should be recovering.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgareunclean
    expr: |
      ceph_pg_total{job="ceph"} - ceph_pg_clean{job="ceph"} != 0
    for: 30m
    labels:
      severity: warning
- name: systemd
  rules:
  - alert: CephSystemdUnitIsNotActive
    annotations:
      description: Systemd unit {{$labels.name}} is not active.
      grafana_url: ""
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephsystemdunitisnotactive
    expr: |
      node_systemd_unit_state{name=~"ceph.*", state="active"} != 1
    labels:
      severity: critical
