groups:
- name: ceph-absent
  rules:
  - alert: CephMgrIsAbsent
    annotations:
      message: Ceph Manager has disappeared from Prometheus target discovery.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmgrisabsent
    expr: |
      absent(up{job="ceph"} == 1)
    for: 5m
    labels:
      severity: critical
- name: ceph-down
  rules:
  - alert: CephMgrIsMissingReplicas
    annotations:
      message: Ceph Manager is missing replicas.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmgrismissingreplicas
    expr: |
      sum(up{job="ceph"}) != 3
    for: 5m
    labels:
      severity: warning
- name: ceph-osd
  rules:
  - alert: CephOSDDown
    annotations:
      message: '{{$labels.ceph_daemon}} Ceph OSD is down.'
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosddown
    expr: |
      ceph_osd_up{job="ceph"} != 1
    labels:
      severity: warning
  - alert: CephOSDNotIn
    annotations:
      message: '{{$labels.ceph_daemon}} Ceph OSD is out of the cluster, CRUSH will
        not assign placement groups to the OSD.'
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosdnotin
    expr: |
      ceph_osd_in{job="ceph"} != 1
    labels:
      severity: warning
  - alert: CephOSDLowSpace
    annotations:
      message: '{{$labels.ceph_daemon}} Ceph OSD used more than 85 % of disk space.'
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosdlowspace
    expr: |
      (ceph_osd_stat_bytes_used{job="ceph"} / ceph_osd_stat_bytes{job="ceph"}) * 100 > 85
    labels:
      severity: warning
- name: ceph-mon
  rules:
  - alert: CephMonInsufficientMembers
    annotations:
      message: 'Ceph Monitor "{{ $labels.job }}": insufficient members ({{ $value
        }}).'
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmoninsufficientmembers
    expr: |
      sum(ceph_mon_quorum_status{job="ceph"} == bool 1) by (job) < ((count(ceph_mon_quorum_status{job="ceph"}) by (job) + 1) / 2)
    labels:
      severity: warning
  - alert: CephMonNoQuorum
    annotations:
      message: 'Ceph Monitor "{{ $labels.job }}": member {{ $labels.instance }} has
        no quorum.'
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonnoquorum
    expr: |
      ceph_mon_quorum_status{job="ceph"} == 0
    for: 1m
    labels:
      severity: critical
  - alert: CephMonHighNumberOfLeaderChanges
    annotations:
      message: 'Ceph Monitor "{{ $labels.job }}": instance {{ $labels.instance }}
        has seen {{ $value }} leader changes within the last 30 minutes.'
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonhighnumberofleaderchanges
    expr: |
      rate(ceph_mon_num_elections{job="ceph"}[15m]) > 3
    for: 15m
    labels:
      severity: warning
  - alert: CephMonQuorumStatus
    annotations:
      message: Ceph Monitor reporting bad quorum status.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonquorumstatus
    expr: |
      ceph_mon_quorum_status{job="ceph"} != 1
    labels:
      severity: critical
- name: ceph-pg
  rules:
  - alert: CephPGAreNotActive
    annotations:
      message: Some Placement Groups are not active.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgarenotactive
    expr: |
      ceph_pg_total{job="ceph"} - ceph_pg_active{job="ceph"} != 0
    labels:
      severity: critical
  - alert: CephPGAreUnclean
    annotations:
      message: Placement groups contain objects that are not replicated the desired
        number of times. They should be recovering.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgareunclean
    expr: |
      ceph_pg_total{job="ceph"} - ceph_pg_clean{job="ceph"} != 0
    for: 30m
    labels:
      severity: warning
- name: ceph-system
  rules:
  - alert: CephHealthStatusErr
    annotations:
      message: Ceph Healh status is ERR.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephhealthstatuserr
    expr: "ceph_health_status{job=\"ceph\"} == 2 \n"
    labels:
      severity: critical
  - alert: CephHealthStatusWarn
    annotations:
      message: Ceph Healh status is WARN.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephhealthstatuswarn
    expr: |
      ceph_health_status{job="ceph"} == 1
    labels:
      severity: warning
  - alert: CephOSDVersionMismatch
    annotations:
      message: There are {{ $value }} different versions of Ceph OSD components running.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosdversionmismatch
    expr: |
      count(count(ceph_osd_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 1h
    labels:
      severity: warning
  - alert: CephMonVersionMismatch
    annotations:
      message: There are {{ $value }} different versions of Ceph OSD components running.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonversionmismatch
    expr: |
      count(count(ceph_mon_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 1h
    labels:
      severity: warning
