groups:
- name: quorum-alert.rules
  rules:
  - alert: CephMonQuorumAtRisk
    annotations:
      description: Storage cluster quorum is low. Contact Support.
      message: Storage quorum at risk
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonquorumatrisk
      severity_level: error
      storage_type: ceph
    expr: |
      count(ceph_mon_quorum_status == 1) <= ((count(ceph_mon_metadata) % 2) + 1)
    for: 15m
    labels:
      severity: critical
- name: ceph-node-alert.rules
  rules:
  - alert: CephNodeDown
    annotations:
      description: Storage node {{ $labels.node }} went down. Please check the node
        immediately.
      message: Storage node {{ $labels.node }} went down
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephnodedown
      severity_level: error
      storage_type: ceph
    expr: |
      cluster:ceph_node_down:join_kube
    for: 30s
    labels:
      severity: critical
- name: osd-alert.rules
  rules:
  - alert: CephOSDDiskNotResponding
    annotations:
      description: Disk device {{ $labels.device }} not responding, on host {{ $labels.host
        }}.
      message: Disk not responding
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosddisknotresponding
      severity_level: error
      storage_type: ceph
    expr: |
      label_replace((ceph_osd_in == 1 and ceph_osd_up == 0),"disk","$1","ceph_daemon","osd.(.*)") + on(ceph_daemon) group_left(host, device) label_replace(ceph_disk_occupation,"host","$1","exported_instance","(.*)")
    for: 1m
    labels:
      severity: critical
  - alert: CephOSDDiskUnavailable
    annotations:
      description: Disk device {{ $labels.device }} not accessible on host {{ $labels.host
        }}.
      message: Disk not accessible
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosddiskunavailable
      severity_level: error
      storage_type: ceph
    expr: |
      label_replace((ceph_osd_in == 0 and ceph_osd_up == 0),"disk","$1","ceph_daemon","osd.(.*)") + on(ceph_daemon) group_left(host, device) label_replace(ceph_disk_occupation,"host","$1","exported_instance","(.*)")
    for: 1m
    labels:
      severity: critical
  - alert: CephDataRecoveryTakingTooLong
    annotations:
      description: Data recovery has been active for more than 2h. Contact Support.
      message: Data recovery is slow
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephdatarecoverytakingtoolong
      severity_level: warning
      storage_type: ceph
    expr: |
      ceph_pg_undersized > 0
    for: 2h
    labels:
      severity: warning
  - alert: CephPGRepairTakingTooLong
    annotations:
      description: Self heal operations taking too long. Contact Support.
      message: Self heal problems detected
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgrepairtakingtoolong
      severity_level: warning
      storage_type: ceph
    expr: |
      ceph_pg_inconsistent > 0
    for: 1h
    labels:
      severity: warning
- name: cluster-state-alert.rules
  rules:
  - alert: CephClusterErrorState
    annotations:
      description: Storage cluster is in error state for more than 10m.
      message: Storage cluster is in error state
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclustererrorstate
      severity_level: error
      storage_type: ceph
    expr: |
      ceph_health_status{job="ceph"} > 1
    for: 10m
    labels:
      severity: critical
  - alert: CephClusterWarningState
    annotations:
      description: Storage cluster is in warning state for more than 10m.
      message: Storage cluster is in degraded state
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclusterwarningstate
      severity_level: warning
      storage_type: ceph
    expr: |
      ceph_health_status{job="ceph"} == 1
    for: 10m
    labels:
      severity: warning
  - alert: CephOSDVersionMismatch
    annotations:
      description: There are {{ $value }} different versions of Ceph OSD components
        running.
      message: There are multiple versions of storage services running.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosdversionmismatch
      severity_level: warning
      storage_type: ceph
    expr: |
      count(count(ceph_osd_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 10m
    labels:
      severity: warning
  - alert: CephMonVersionMismatch
    annotations:
      description: There are {{ $value }} different versions of Ceph Mon components
        running.
      message: There are multiple versions of storage services running.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonversionmismatch
      severity_level: warning
      storage_type: ceph
    expr: |
      count(count(ceph_mon_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 10m
    labels:
      severity: warning
- name: cluster-utilization-alert.rules
  rules:
  - alert: CephClusterNearFull
    annotations:
      description: Storage cluster utilization has crossed 85%.
      message: Storage cluster is nearing full. Expansion is required.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclusternearfull
      severity_level: warning
      storage_type: ceph
    expr: |
      sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.85
    for: 5m
    labels:
      severity: warning
  - alert: CephClusterCriticallyFull
    annotations:
      description: Storage cluster utilization has crossed 95%.
      message: Storage cluster is critically full and needs immediate expansion
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephclustercriticallyfull
      severity_level: error
      storage_type: ceph
    expr: |
      sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.95
    for: 5m
    labels:
      severity: critical
- name: ceph-pg
  rules:
  - alert: CephPGAreNotActive
    annotations:
      component: ceph-osd
      grafana_url: ""
      message: Some Placement Groups are not active.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgarenotactive
    expr: |
      ceph_pg_total{job="ceph"} - ceph_pg_active{job="ceph"} != 0
    labels:
      severity: critical
  - alert: CephPGAreUnclean
    annotations:
      component: ceph-osd
      grafana_url: ""
      message: Placement groups contain objects that are not replicated the desired
        number of times. They should be recovering.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephpgareunclean
    expr: |
      ceph_pg_total{job="ceph"} - ceph_pg_clean{job="ceph"} != 0
    for: 30m
    labels:
      severity: warning
- name: ceph-system
  rules:
  - alert: CephHealthStatusErr
    annotations:
      component: general
      grafana_url: ""
      message: Ceph Healh status is ERR.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephhealthstatuserr
    expr: "ceph_health_status{job=\"ceph\"} == 2 \n"
    labels:
      severity: critical
  - alert: CephHealthStatusWarn
    annotations:
      component: general
      grafana_url: ""
      message: Ceph Healh status is WARN.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephhealthstatuswarn
    expr: |
      ceph_health_status{job="ceph"} == 1
    labels:
      severity: warning
  - alert: CephOSDVersionMismatch
    annotations:
      component: ceph-osd
      grafana_url: ""
      message: There are {{ $value }} different versions of Ceph OSD components running.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephosdversionmismatch
    expr: |
      count(count(ceph_osd_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 1h
    labels:
      severity: warning
  - alert: CephMonVersionMismatch
    annotations:
      component: ceph-monitor
      grafana_url: ""
      message: There are {{ $value }} different versions of Ceph OSD components running.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephmonversionmismatch
    expr: |
      count(count(ceph_mon_metadata{job="ceph"}) by (ceph_version)) > 1
    for: 1h
    labels:
      severity: warning
- name: systemd
  rules:
  - alert: CephSystemdUnitIsNotActive
    annotations:
      component: general
      grafana_url: ""
      message: Systemd unit {{$labels.name}} is not active.
      runbook_url: https://github.com/devopyio/ceph-monitoring-mixin/tree/master/runbook.md#alert-name-cephsystemdunitisnotactive
    expr: |
      node_systemd_unit_state{name=~"ceph.*", state="active"} != 1
    labels:
      severity: critical
